/*
 * Copyright 2008-2010 Digital Enterprise Research Institute (DERI)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.deri.any23.extractor.html;

import org.deri.any23.validator.Report;
import org.w3c.dom.Document;

/**
 * Represents the report generated by a
 * the {@link org.deri.any23.extractor.html.TagSoupParser} when a document
 * is retrieved and validated.
 *
 * @author Michele Mostarda (mostarda@fbk.eu)
 * @author Davide Palmisano (palmisano@fbk.eu)
 */
public class DocumentReport {

    private Report report;
    private Document document;

    public DocumentReport(Report report, Document document) {
        this.report = report;
        this.document = document;
    }

    public Report getReport() {
        return report;
    }

    public Document getDocument() {
        return document;
    }

}
