/*
 * Copyright 2008-2010 Digital Enterprise Research Institute (DERI)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.deri.any23.vocab;

import org.openrdf.model.URI;

import java.util.HashMap;
import java.util.Map;

/**
 * Vocabulary definitions from vocabularies/review.rdf
 *
 * @author Auto-generated by schemagen
 */
public class REVIEW extends Vocabulary {

    /**
     * The namespace of the vocabulary as a string.
     */
    public static final String NS = "http://purl.org/stuff/rev#";

    /**
     * The namespace of the vocabulary as a URI.
     */
    public static final URI NAMESPACE = createURI(NS);

    /**
     * The commenter on the review.
     */
    public static final URI commenter =  createProperty("commenter");

    /**
     * Used to associate a review with a comment on the review.
     */
    public static final URI hasComment = createProperty("hasComment");

    /**
     * Associates a review with a feedback on the review.
     */
    public static final URI hasFeedback = createProperty("hasFeedback");

    /**
     * Associates a work with a a review.
     */
    public static final URI hasReview = createProperty("hasReview");

    /**
     * A numeric value.
     */
    public static final URI maxRating = createProperty("maxRating");

    /**
     * A numeric value.
     */
    public static final URI minRating = createProperty("minRating");

    /**
     * Number of positive usefulness votes (integer).
     */
    public static final URI positiveVotes = createProperty("positiveVotes");

    /**
     * A numeric value.
     */
    public static final URI rating = createProperty("rating");

    /**
     * The person that has written the review.
     */
    public static final URI reviewer = createProperty("reviewer");

    /**
     * The text of the review.
     */
    public static final URI text = createProperty("text");

    /**
     * The title of the review.
     */
    public static final URI title = createProperty("title");

    /**
     * Number of usefulness votes (integer).
     */
    public static final URI totalVotes = createProperty("totalVotes");

    /**
     * The type of media of a work under review.
     */
    public static final URI type = createProperty("type");

    /**
     * A comment on a review.
     */
    public static final URI Comment = createProperty("Comment");

    /**
     * Feedback on the review. Expresses whether the review was useful or not.
     */
    public static final URI Feedback = createProperty("Feedback");

    /**
     * A review of an work.
     */
    public static final URI Review = createProperty("Review");

    private static Map<String, URI> propertyMap;

    /**
     * The namespace of the vocabulary as a string.
     *
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

    private static URI createProperty(String localName) {
        if (propertyMap == null) {
            propertyMap = new HashMap<String, URI>();
        }
        URI result = createURI("http://purl.org/stuff/rev#" + localName);
        propertyMap.put(localName, result);
        return result;
    }

    private REVIEW(){}

}
